### ISSUE TITLE
Colon in Ids are not supported

### ISSUE THREAD

**Issue by totemcaf** [warrant-dev/warrant#106]
**Describe the bug**

If you create, for example, a permission with a colon ":" in the ID, a query on that instance produce an Internal Server Error.

**To Reproduce**
1. Given a installation
2. Create a user
3. Create a Permission with ID "this:is-a-permission"
4. Assign permission to the user
1. Go to Fine Grained Access Control page
5. Click on 'Check'
6. You will see the page with query: `SELECT EXPLICIT warrant`
7. You will see a message "Invalid query"
8. Check browser developer console, you will see the response from server "500 Internal server error".

In the UI:

![image](https://user-images.githubusercontent.com/759079/235788323-40a2c37c-b2e1-4860-88ec-35fa737f744e.png)

Server response:

`{"code":"internal_error","message":"Internal Server Error"}
`
**Expected behavior**

It could be one of the two:

1. An error is reported disallowing the creation of an object with an ID having a colon
2. The query success showing the first page of warrants

**Additional context**

I guess that because the colon is used as separator between object type and object id, it could be a restriction to use the colon in the object IDs.

We were using colon to organizar permissions (like `user:create`) so I tried for that specific case.

**Comment by kkajla12** [comment]
@totemcaf, thanks for letting us know about this issue. We've started working on a fix to support colons in object/subject ids. In the mean time, you can still use a different naming scheme for organizing permissions (e.g. `user-create`). Sorry for the inconvenience.

**Comment by kkajla12** [comment]
Support for colons in object ids has been added as of [v0.13.0](https://github.com/warrant-dev/warrant/releases/tag/v0.13.0)
