### ISSUE TITLE
/v1/query API is missing

### ISSUE THREAD

**Issue by keimoon** [warrant-dev/warrant#193]
/v1/query API is stated here in the API reference https://docs.warrant.dev/warrants/query-warrants/ but the local warrant server returns not found.

**Comment by akajla09** [comment]
Hi @keimoon - the query api is currently only available on Warrant cloud. You can try it out with a [cloud service account](https://app.warrant.dev/signup).

**Comment by kkajla12** [comment]
Hi @keimoon, in case you're just looking to list warrants using specific filters (e.g. `objectType`, `objectId`, etc.), you can also make use of the [List Warrants endpoint](https://docs.warrant.dev/warrants/get-warrants/) which is supported by the open source version of Warrant.

**Comment by kkajla12** [comment]
@keimoon, support for the Query API was added in #225.
