### ISSUE TITLE
Support one time use warrants

### ISSUE THREAD

**Issue by samarth-ramesh** [warrant-dev/warrant#60]
An operator at a front desk wants to make a transaction above a certain threshold. To go ahead, the auth system must require another user with a certain role (“supervisor” say) to authorize this. To actually authorize this, the supervisor will create a warrant. This warrant should allow the operator to make the transaction, but only once. Further transactions must require fresh authentication. Furthermore, this warrant must expire in some time (say 5 minutes).

Warrants could have an optional added field for “max_uses”, “expiresat”

**Describe alternatives you've considered**
I have considered modifying my application to create and take down the warrant. However, I can foresee it getting messy and error-prone (consequently insecure and incorrect)

**Comment by akajla09** [comment]
Thanks for the submission @samarth-ramesh . We'll review this and come back with a proposal/implementation.

Notes:
- Will need to add an "expiresAt" or "validity" field to warrants and enforce that in the authz check

**Comment by kkajla12** [comment]
@samarth-ramesh, closing this issue as this is now possible (as of #140 and #147) using [policies & context](https://docs.warrant.dev/concepts/warrants/#policies--context). Using the built-in `[expiresIn](https://docs.warrant.dev/concepts/warrants/#expiresinduration)` method, you can create warrants that automatically expire in a set amount of time (e.g. 5m, 24h, etc).
