### ISSUE TITLE
Generate Docker images for additional architectures

### ISSUE THREAD

**Issue by akajla09** [warrant-dev/warrant#69]
**Is your feature request related to a problem? Please describe.**
Currently, the only Docker image generated from the release pipeline is for linux/amd64 (built on the bare alpine img). We should consider adding images for arm (Mac etc).

**Describe the solution you'd like**
Goreleaser already generates Go binaries for multiple architectures, including arm and windows. We should also build [appropriate Docker images](https://github.com/warrant-dev/warrant/blob/main/.goreleaser.yaml#L42).

Note: might have to pick a different base image (some research required)

**Describe alternatives you've considered**
Go binaries for other architectures are still built and [available for download](https://github.com/warrant-dev/warrant/releases) in case needed.

**Comment by kkajla12** [comment]
Support for this was added in #200.
