### ISSUE TITLE
Create pub sub connector(s) for events

### ISSUE THREAD

**Issue by kkajla12** [warrant-dev/warrant#90]
**Is your feature request related to a problem? Please describe.**
Currently, Warrant's event store can be configured to track and persist events to a database (MySQL, Postgres, SQLite, etc). We should explore support for publishing events to pub sub systems like Kafka, SNS, etc.

**Describe the solution you'd like**
Warrant should add support for publishing events to pub sub systems like Kafka, SNS, etc. This would involve writing an event repository for each supported pub sub system that knows how to publish the events.

**Describe alternatives you've considered**
N/A

**Additional context**
We'll need to consider how the list events endpoints would work in the scenario that the event store was configured to publish events to a pub sub service. More than likely, these endpoints would not be supported in that case because the events would be sent outside of Warrant.

**Comment by akajla09** [comment]
> We'll need to consider how the list events endpoints would work in the scenario that the event store was configured to publish events to a pub sub service. More than likely, these endpoints would not be supported in that case because the events would be sent outside of Warrant.

I would argue that we support multiple 'sinks' in this case (i.e. events are published to a stream AND to a persisted store like mysql)
